config/routes.rb
Rails.application.routes.draw do
  resources :rolecall, only: [:index] do
    collection do
      put :complete
      get :update_session_id
    end
  end
  resources :speechlist, only: [:index] do
    collection do
      put :complete
      post :add_poi
      get :update_poi
      get :update_mark
      get :filter
      get :delete_poi
      get :delete_mark
    end
  end
  resources :mod, only: [:index] do
    collection do
      post :add_topic
      get :delete_topic
      get :update_topic_mark

      get :update_speech
      get :delete_speech
      post :add_speech
    end
  end
  root to: 'pages#index'
end

app/models/committee.rb
class Committee < ActiveRecord::Base
  belongs_to :day
  has_many :delegates, dependent: :destroy

  def delegates
    Delegate.where('committee_id = ?', id)
  end

  def absent_delegates(session_num)
    Delegate.where("committee_id = ? AND session#{session_num} = false", id)
  end

  def spoken_delegates
    Delegate.where('speech IS NOT NULL AND committee_id = ?', id)
  end

  def to_speak_delegates
    Delegate.where('to_speech IS TRUE AND speech IS NULL AND committee_id = ?', id)
  end

  def not_to_speak_delegates
    Delegate.where('to_speech IS FALSE AND committee_id = ?', id)
  end

  def filter_delegates(string)
    Delegate.where("LOWER(country) like lower('%#{string}%') AND committee_id = ? AND to_speech IS TRUE", id)
  end

  def poi_delegates(country)
    delegates = []
    delegate_to = Delegate.find_by(country: country, committee_id: id)
    valid_poi_delegates = Delegate.where("country != '#{country}' AND committee_id = ?", id)
    valid_poi_delegates.each do |delegate|
      delegates.push(delegate) unless PoiSpeech.find_by(country: delegate.country, delegate_id: delegate_to.id)
    end
    delegates
  end

  def mod_topics
    ModTopic.where('delegate_id IN (?)', delegates.ids)
  end
end

app/controllers/mod_controller.rb
class ModController < ApplicationController
  def add_topic
    @delegate_id = params[:delegate_id]
    @delegate_country = Delegate.find(@delegate_id).country
    @title = params[:title]
    ModTopic.create(delegate_id: @delegate_id, title: @title)
  end

  def delete_topic
    @topic_id = params[:topic_id]
    @topic = ModTopic.find(@topic_id)
    @topic.destroy
  end

  def update_topic_mark
    @mark = params[:mark]
    @topic_id = params[:topic_id]
    ModTopic.where('id = ?', @topic_id).update_all(mark: @mark.to_i)
    @topic = ModTopic.find(@topic_id)
  end

  def update_speech
    @topic_id = params[:topic_id]
    @mark = params[:mark]
    @delegate_by_country = params[:country]
    ModSpeech.where("mod_topic_id = #{@topic_id} AND country = '#{@delegate_by_country}'").update_all(mark: @mark.to_i)
  end

  def delete_speech
    @speech_id = params[:speech_id]
    @speech_country = ModSpeech.find(@speech_id).country
    ModSpeech.find(@speech_id).destroy
  end

  def add_speech
    @topic_id = params[:topic_id]
    @delegate_ids = params[:delegate_ids]
    @delegate_to_country = params[:delegate_to_country]

    @delegate_ids = Delegate.find(params[:delegate_ids])
    @delegate_ids.each do |delegate|
      ModSpeech.create(mod_topic_id: @topic_id, country: delegate.country)
    end
  end
end

app/helpers/mod_helper.rb
module ModHelper
  def mod_topics
    Day.first.committees.first.mod_topics
  end
  def delegates
    Day.first.committees.first.delegates
  end

  def speech_delegates(topic_id)
    delegates =[]
    @delegate_to = Delegate.find(ModTopic.find(topic_id).delegate_id)
    valid_topic_delegates = Delegate.where("country != '#{@delegate_to.country}' AND committee_id = ?", @delegate_to.committee_id)
    valid_topic_delegates.each do |delegate|
      delegates.push(delegate) unless ModSpeech.find_by(country: delegate.country, mod_topic_id: topic_id )
    end
    delegates
    end
end

app/views/mod/_add_to_speech_modal.html.haml
.modal.black-text{id: 'modal_' + topic_id.to_s}
  .modal-content
    %h5 Add POI delegates
    - if speech_delegates(topic_id).any?
      = form_tag add_speech_mod_index_path, remote: true,  method: :post do
        %ul.rolecall-delegates
          - speech_delegates(topic_id).each do |delegate|
            %li
              %p
                = hidden_field_tag('topic_id', value = topic_id)
                = hidden_field_tag('delegate_to_country', value = topic_country)
                = check_box_tag "delegate_ids[]", delegate.id, nil, id: "for_#{topic_country}_delegate_ids_#{delegate.id}"
                = label_tag "for_#{topic_country}_delegate_ids[#{delegate.id}]", delegate.country
        .modal-footer
          = submit_tag "Add to Speaker's List", class: 'btn  indigo lighten-1'
    - else
      %p.black-text All Delegates have made a Speech for this topic !

app/views/mod/_add_to_topic_modal.html.haml
#modal1.modal.black-text
  .modal-content
    %h5 Add a Moderated Caucus Topics
    = form_tag add_topic_mod_index_path, remote: true,  method: :post do
      .spacer-modal-form
      .input-field
        = text_field_tag 'title', nil,  required: true
        = label_tag 'title'
      .input-field
        = select_tag "delegate_id", options_from_collection_for_select(delegates, "id", "country"), class: 'browser-default'
      .modal-footer
        = submit_tag "Add to Speaker's List", class: 'btn  indigo lighten-1'

app/views/mod/_fab.html.haml
.fixed-action-btn{:style => "bottom: 45px; right: 24px;"}
  %a.btn-floating.btn-large.red.modal-trigger.modal-close{href: '#modal1'}
    %i.large.material-icons add
  -# %ul
  -#   %li
  -#     %a.btn-floating.red
  -#       %i.material-icons insert_chart

app/views/mod/_session_content.html.haml
- if mod_topics.any?
  %ul.collapsible.black-text{"data-collapsible" => "expandable"}
    - mod_topics.each do |topic|
      = render(partial: 'topic_list', locals: {topic: topic})
:javascript
  $(document).ready(function(){
    $('.collapsible').collapsible({
          accordion : false
        });
    $(".collapsible-header a").click(function(e) {
      e.stopPropagation();
    });

    $('.topic-list-score').on('change', function() {
      $.ajax({
         url: "#{update_topic_mark_mod_index_path}",
         data: {
             mark: $(this).val(),
             topic_id: $(this).attr('name')
         },
         dataType: "script"
      });
    });
    $('.topic-list-speech-score').on('change', function() {
      $.ajax({
         url: "#{update_speech_mod_index_path}",
         data: {
             mark: $(this).val(),
             country: $(this).attr('country'),
             topic_id: $(this).attr('topic_id')
         },
         dataType: "script"
      });
    });
    $(".delete-topic").click(function(){
      if (confirm("You are about to delete the Topic submitted by " + $(this).attr('delegate_country') , " are you sure ?")){
        $.ajax({
           url: "#{delete_topic_mod_index_path}",
           data: {
               topic_id: $(this).attr('topic_id')
           },
           dataType: "script"
        });
      }
    });
    $(".delete-speech").click(function(){
      if (confirm("You are about to delete the speech by " + $(this).attr('country') , " are you sure ?")){
        $.ajax({
           url: "#{delete_speech_mod_index_path}",
           data: {
               speech_id: $(this).attr('speech_id')
           },
           dataType: "script"
        });
      }
    });
    
  });

app/views/mod/_speech.html.haml
.col.s10
  %ul.collapsible.black-text
    - topic.mod_speeches.each do |speech|
      %li
        .collapsible-header
          .col.s4
            = speech.country
          .col.s5
            .input-field.poi-input
              %input.validate.topic-list-speech-score{:placeholder => "Score", :type => "number", min: 0, max: 10, country: speech.country, value: speech.mark, topic_id: topic.id }
          %a.btn-floating.btn-floating-speaker-list.btn-small.waves-effect.waves-light.red.right.delete-speech{speech_id: speech.id, country: speech.country}
            %i.material-icons remove

app/views/mod/_topic_list.html.haml
%li
  .collapsible-header
    %a.btn-floating.btn-floating-speaker-list.btn-small.waves-effect.waves-light.teal.add-icon{id: "modal_link_#{topic.id}" }
      %i.material-icons add
    %a.btn-floating.btn-floating-speaker-list.btn-small.waves-effect.waves-light.red.right.delete-topic{topic_id: topic.id,
    delegate_country: topic.delegate.country}
      %i.material-icons remove
    = topic.title
  .collapsible-body
    .row.speaker-list-row
      .col.s2.input-field.speech-input
        .z-depth-1.score
          %input.topic-list-score.validate{:placeholder => "Score", :type => "number", min: 0, max: 10, value: topic.mark, name: topic.id}
      - if topic.has_mod_speeches?
        = render 'speech', topic: topic
  .topic-modal
    = render(partial: 'add_to_speech_modal', locals: {topic_country: topic.delegate.country, topic_id: topic.id, delegate_to_id:topic.delegate.id} )


:javascript
  $(document).ready(function(){
    $("#modal_link_#{topic.id}").click(function() {
      $("#modal_#{topic.id}").openModal();
    });

  });

app/views/mod/add_speech.js.erb
$("#modal_<%= escape_javascript(@topic_id) %>").closeModal();
$('#session_content').html( "<%= escape_javascript( render 'session_content') %>")
Materialize.toast("Speech added for <%= escape_javascript(@delegate_to_country) %> !", 4000);

app/views/mod/add_topic.js.erb
$("#modal1").closeModal();
$('#session_content').html( "<%= escape_javascript( render 'session_content') %>");
Materialize.toast("Added a Moderated Caucus topic by <%= escape_javascript(@delegate_country) %> !", 4000);

app/views/mod/delete_speech.js.erb
$('#session_content').html( "<%= escape_javascript( render 'session_content') %>");
Materialize.toast("Deleted the speech by <%= escape_javascript(@speech_country) %> !", 4000);

app/views/mod/delete_topic.js.erb
$('#session_content').html( "<%= escape_javascript( render 'session_content') %>");
Materialize.toast("Deleted a Moderated Caucus topic by <%= escape_javascript(@topic.delegate.country) %> !", 4000);

app/views/mod/index.html.haml
.row
  .col.s12
    .card.blue.lighten-2
      .card-content.white-text
        %span.card-title#session-title
          Moderated Caucus
          - unless mod_topics.any?
            &mdash; No Topics have been added
        .speak-list-modal
          = render 'add_to_topic_modal'
        #session_content
          = render 'session_content'
    = render 'fab'

app/views/mod/update_speech.js.erb
$('#session_content').html( "<%= escape_javascript( render 'session_content') %>");
Materialize.toast("Updated the score for the speech by <%= escape_javascript(@delegate_by_country) %> !", 4000);

app/views/mod/update_topic_mark.js.erb
$('#session_content').html( "<%= escape_javascript( render 'session_content') %>");
Materialize.toast("Updated the score for the Moderated Caucus topic by <%= escape_javascript(@topic.delegate.country) %> !", 4000);