config/routes.rb
Rails.application.routes.draw do
  resources :rolecall, only: [:index] do
    collection do
      put :complete
      get :update_session_id
    end
  end
  resources :speechlist, only: [:index] do
    collection do
      put :complete
      post :add_poi
      get :update_poi
      get :update_mark
      get :filter
      get :delete_poi
      get :delete_mark
    end
  end
  resources :mod, only: [:index] do
    collection do
      post :add_topic
      get :delete_topic
      get :update_topic_mark

      get :update_speech
      get :delete_speech
      post :add_speech
    end
  end
  root to: 'pages#index'
end

app/models/committee.rb
class Committee < ActiveRecord::Base
  belongs_to :day
  has_many :delegates, dependent: :destroy

  def delegates
    Delegate.where('committee_id = ?', id)
  end

  def absent_delegates(session_num)
    Delegate.where("committee_id = ? AND session#{session_num} = false", id)
  end

  def spoken_delegates
    Delegate.where('speech IS NOT NULL AND committee_id = ?', id)
  end

  def to_speak_delegates
    Delegate.where('to_speech IS TRUE AND speech IS NULL AND committee_id = ?', id)
  end

  def not_to_speak_delegates
    Delegate.where('to_speech IS FALSE AND committee_id = ?', id)
  end

  def filter_delegates(string)
    Delegate.where("LOWER(country) like lower('%#{string}%') AND committee_id = ? AND to_speech IS TRUE", id)
  end

  def poi_delegates(country)
    delegates = []
    delegate_to = Delegate.find_by(country: country, committee_id: id)
    valid_poi_delegates = Delegate.where("country != '#{country}' AND committee_id = ?", id)
    valid_poi_delegates.each do |delegate|
      delegates.push(delegate) unless PoiSpeech.find_by(country: delegate.country, delegate_id: delegate_to.id)
    end
    delegates
  end

  def mod_topics
    ModTopic.where('delegate_id IN (?)', delegates.ids)
  end
end

app/controllers/rolecall_controller.rb
class RolecallController < ApplicationController
  def index
    @session_id = 1
    @delegates = Day.first.committees.first.absent_delegates(1).all
  end

  def complete
    @session_id = params[:session_id]
    @delegate_ids = params[:delegate_ids]
    puts @session_id
    if @session_id == '1'
      Delegate.where('id IN (?)', @delegate_ids).update_all(session1: true)
    elsif @session_id == '2'
      Delegate.where('id IN (?)', @delegate_ids).update_all(session2: true)
    end
    @delegates = Day.first.committees.first.absent_delegates(@session_id).all
    respond_to do |format|
      format.html { redirect_to rolecall_index_path}
      format.js
    end
  end

  def update_session_id
    @session_id = params[:session_id]
    @delegates = Day.first.committees.first.absent_delegates(@session_id).all
  end
end

app/helpers/rolecall_helper.rb
module RolecallHelper  
end

app/views/rolecall/_session_form.html.haml
= form_tag complete_rolecall_index_path, remote: true,  method: :put do
  - if @delegates.any?
    %ul.rolecall-delegates
      = hidden_field_tag :session_id, @session_id.to_i
      - @delegates.each do |delegate|
        %li
          %p
            = check_box_tag "delegate_ids[]", delegate.id, nil, id: "delegate_ids_#{delegate.id}"
            = label_tag "delegate_ids[#{delegate.id}]", delegate.country
    = submit_tag "Mark as Present", class: 'btn  indigo lighten-1'
  - else
    %p.white-text All Delegates are present !

app/views/rolecall/complete.js.erb
$('#session-title').html("Rolecall Session <%= @session_id %> ")
$('#session_content').html("<%= escape_javascript(render 'session_form') %> ")

app/views/rolecall/index.html.haml
.row
  .col.s12
    .input-field
      %select#session_id
        %option{value: 1} Session 1
        %option{value: 2} Session 2

    .card.blue.lighten-2
      .card-content.black-text
        %span.card-title#session-title Rolecall Session 1
        #session_content
          = render 'session_form'

:javascript
  $(document).ready(function() {
    $('#session_id').on('change', function() {
      $('#session-title').html(" <div class='center-align'>Give us a second ... </div>" );
      $('#session_content').html("#{escape_javascript(render 'shared/circular_loader')} ");

      $.ajax({
         url: "#{update_session_id_rolecall_index_path}",
         data: {
             session_id: $("#session_id option:selected").val()
         },
         dataType: "script"
      });
    });
  });

app/views/rolecall/update_session_id.js.erb
$('#session-title').html("Rolecall Session <%= @session_id %> ")
$('#session_content').html("<%= escape_javascript(render 'session_form') %> ")