config/routes.rb
Rails.application.routes.draw do
  resources :rolecall, only: [:index] do
    collection do
      put :complete
      get :update_session_id
    end
  end
  resources :speechlist, only: [:index] do
    collection do
      put :complete
      post :add_poi
      get :update_poi
      get :update_mark
      get :filter
      get :delete_poi
      get :delete_mark
    end
  end
  resources :mod, only: [:index] do
    collection do
      post :add_topic
      get :delete_topic
      get :update_topic_mark

      get :update_speech
      get :delete_speech
      post :add_speech
    end
  end
  root to: 'pages#index'
end

app/models/committee.rb
class Committee < ActiveRecord::Base
  belongs_to :day
  has_many :delegates, dependent: :destroy

  def delegates
    Delegate.where('committee_id = ?', id)
  end

  def absent_delegates(session_num)
    Delegate.where("committee_id = ? AND session#{session_num} = false", id)
  end

  def spoken_delegates
    Delegate.where('speech IS NOT NULL AND committee_id = ?', id)
  end

  def to_speak_delegates
    Delegate.where('to_speech IS TRUE AND speech IS NULL AND committee_id = ?', id)
  end

  def not_to_speak_delegates
    Delegate.where('to_speech IS FALSE AND committee_id = ?', id)
  end

  def filter_delegates(string)
    Delegate.where("LOWER(country) like lower('%#{string}%') AND committee_id = ? AND to_speech IS TRUE", id)
  end

  def poi_delegates(country)
    delegates = []
    delegate_to = Delegate.find_by(country: country, committee_id: id)
    valid_poi_delegates = Delegate.where("country != '#{country}' AND committee_id = ?", id)
    valid_poi_delegates.each do |delegate|
      delegates.push(delegate) unless PoiSpeech.find_by(country: delegate.country, delegate_id: delegate_to.id)
    end
    delegates
  end

  def mod_topics
    ModTopic.where('delegate_id IN (?)', delegates.ids)
  end
end

app/controllers/speechlist_controller.rb
class SpeechlistController < ApplicationController
  include SpeechlistHelper
  def index
  end

  def complete
    @delegate_ids = params[:delegate_ids]
    Delegate.where('id IN (?)', @delegate_ids).update_all(to_speech: true)
    @delegates = Day.first.committees.first.absent_delegates(@session_id).all
    respond_to do |format|
      format.html { redirect_to speechlist_index_path }
      format.js
    end
  end

  def update_mark
    @delegate_id = params[:delegate_id]
    @mark = params[:mark]
    Delegate.find(@delegate_id).update(speech: @mark)
    respond_to do |format|
      format.html { redirect_to speechlist_index_path }
      format.js
    end
  end

  def filter
    @name = params[:country_name]
    @delegates = filter_delegates(@name)
  end

  def update_poi
    @delegate_to = Day.first.committees.first.delegates.find(params[:delegate_id])
    @delegate_from = Day.first.committees.first.delegates.find_by_country(params[:country])
    @poi_speech = @delegate_to.poi_speeches.find_by_country(params[:country])
    @new_mark = params[:mark].to_i
    @delegate_from.update(poi_score: @delegate_from.poi_score + (@new_mark - @poi_speech.mark))
    @poi_speech.update(mark: @new_mark)
    respond_to do |format|
      format.html { redirect_to speechlist_index_path }
      format.js
    end
  end

  def add_poi
    @delegate_to = params[:delegate_to]
    @delegate_to_country = params[:delegate_to_country]
    @delegate_ids = Delegate.find(params[:delegate_ids])
    @delegate_ids.each do |delegate|
      PoiSpeech.create(delegate_id: @delegate_to, country: delegate.country)
    end
  end
  def delete_mark
    @delegate_id = params[:delegate_id]
    if Delegate.find(@delegate_id)
      Delegate.where('id = ?', @delegate_id).update_all(speech: nil, to_speech: false)
      @delegate_country = Delegate.find(params[:delegate_id]).country
    end
  end
  def delete_poi
    @delegate_to = params[:delegate_to].to_i
    @delegate_from = params[:delegate_by]
    if PoiSpeech.find_by(delegate_id: @delegate_to, country: @delegate_from).destroy
      @delegate_to = Delegate.find(@delegate_to)
    end
  end
end

app/helpers/speechlist_helper.rb
module SpeechlistHelper
  def spoken_delegates
    Day.first.committees.first.spoken_delegates
  end

  def to_speak_delegates
    Day.first.committees.first.to_speak_delegates
  end

  def not_to_speak_delegates
    Day.first.committees.first.not_to_speak_delegates
  end

  def filter_delegates(string)
    Day.first.committees.first.filter_delegates(string)
  end

  def has_spoken(delegate)
    'blue-grey lighten-5' if delegate.speech?
  end

  def poi_delegates(country)
    Day.first.committees.first.poi_delegates(country)
  end
end

app/views/speechlist/_add_poi_modal.html.haml
.modal.black-text{id: 'modal_' + delegate_country}
  .modal-content
    %h5 Add POI delegates
    - if poi_delegates(delegate_country).any?
      = form_tag add_poi_speechlist_index_path, remote: true,  method: :post do
        %ul.rolecall-delegates
          - poi_delegates(delegate_country).each do |delegate|
            %li
              %p
                = hidden_field_tag('delegate_to', value = delegate_to_id)
                = hidden_field_tag('delegate_to_country', value = delegate_country)
                = check_box_tag "delegate_ids[]", delegate.id, nil, id: "for_#{delegate_country}_delegate_ids_#{delegate.id}"
                = label_tag "for_#{delegate_country}_delegate_ids[#{delegate.id}]", delegate.country
        .modal-footer
          = submit_tag "Add to Speaker's List", class: 'btn  indigo lighten-1'
    - else
      %p.black-text All Delegates have asked a POI from this Delegate !

app/views/speechlist/_add_to_speaker_list_modal.html.haml
#modal1.modal.black-text
  .modal-content
    %h5 Add Delegates to Speaker's List
    - if not_to_speak_delegates.any?
      = form_tag complete_speechlist_index_path, remote: true,  method: :put do
        %ul.rolecall-delegates
          - not_to_speak_delegates.each do |delegate|
            %li
              %p
                = check_box_tag "delegate_ids[]", delegate.id, nil, id: "delegate_ids_#{delegate.id}"
                = label_tag "delegate_ids[#{delegate.id}]", delegate.country
        .modal-footer
          = submit_tag "Add to Speaker's List", class: 'btn  indigo lighten-1'
    - else
      %p.black-text All Delegates have been added to the Speaker's List !

app/views/speechlist/_filter_list.html.haml
%ul.collapsible.black-text{"data-collapsible" => "expandable"}
  - delegates.each do |delegate|
    = render(partial: 'speech', locals: {delegate: delegate, class_name: has_spoken(delegate) })
:javascript
  $(document).ready(function() {
    $('.speaker-list-score').on('change', function() {
      $.ajax({
         url: "#{update_mark_speechlist_index_path}",
         data: {
             mark: $(this).val(),
             delegate_id: $(this).attr('name')
         },
         dataType: "script"
      });
    });
  });

app/views/speechlist/_poi.html.haml
.col.s10
  %ul.collapsible.black-text
    - delegate.poi_speeches.each do |poi|
      %li
        .collapsible-header
          .col.s4
            = poi.country
          .col.s5
            .input-field.poi-input
              %input.validate.speaker-list-poi-score{:placeholder => "Score", :type => "number", min: 0, max: 5, country: poi.country, value: poi.mark, delegate_id: delegate.id }
          %a.btn-floating.btn-floating-speaker-list.btn-small.waves-effect.waves-light.red.right.delete-poi{delegate_to: delegate.id, delegate_by: poi.country,
          delegate_by_country: delegate.country}
            %i.material-icons remove

app/views/speechlist/_speaker_list.html.haml
- if to_speak_delegates.any? or spoken_delegates.any?
  %ul.collapsible.black-text{"data-collapsible" => "expandable"}
    - to_speak_delegates.each do |delegate|
      = render(partial: 'speech', locals: {delegate: delegate, class_name: ''})
    - spoken_delegates.each do |delegate|
      = render(partial: 'speech', locals: {delegate: delegate, class_name: 'blue-grey lighten-5'})
:javascript
  $(document).ready(function(){
    $('.collapsible').collapsible({
          accordion : false
        });

    $('.speaker-list-score').on('change', function() {
      $.ajax({
         url: "#{update_mark_speechlist_index_path}",
         data: {
             mark: $(this).val(),
             delegate_id: $(this).attr('name')
         },
         dataType: "script"
      });
    });
    $('.speaker-list-poi-score').on('change', function() {
      $.ajax({
         url: "#{update_poi_speechlist_index_path}",
         data: {
             mark: $(this).val(),
             country: $(this).attr('country'),
             delegate_id: $(this).attr('delegate_id')
         },
         dataType: "script"
      });
    });
    $(".collapsible-header a").click(function(e) {
      e.stopPropagation();
    });
    $(".delete-speech").click(function() {
      if (confirm("You are about to delete the speech by " + $(this).attr('delegate_country') + ", are you sure ?")){
        $.ajax({
           url: "#{delete_mark_speechlist_index_path}",
           data: {
               delegate_id: $(this).attr('delegate_id')
           },
           dataType: "script"
        });
      }
    });
    $(".delete-poi").click(function() {
      if (confirm("You are about to delete the POI by " + $(this).attr('delegate_by') + " for " + $(this).attr('delegate_by_country') + ", are you sure ?")){
        $.ajax({
           url: "#{delete_poi_speechlist_index_path}",
           data: {
               delegate_to: $(this).attr('delegate_to'),
               delegate_by: $(this).attr('delegate_by')
           },
           dataType: "script"
        });
      }
    });
  });

app/views/speechlist/_speech.html.haml
%li
  .collapsible-header{class: class_name}
    %a.btn-floating.btn-floating-speaker-list.btn-small.waves-effect.waves-light.teal.add-icon{id: 'modal_link_' + delegate.country}
      %i.material-icons add
    %a.btn-floating.btn-floating-speaker-list.btn-small.waves-effect.waves-light.red.right.delete-speech{delegate_id: delegate.id, delegate_country: delegate.country}
      %i.material-icons remove
    = delegate.country
  .collapsible-body
    .row.speaker-list-row
      .col.s2.input-field.speech-input
        .z-depth-1.score
          %input.speaker-list-score.validate{:placeholder => "Score", :type => "number", min: 0, max: 10, name: delegate.id, value: delegate.speech }
      - if delegate.has_poi?
        .poi
          = render(partial: 'poi', locals: {delegate: delegate} )
  .poi-modal
    = render(partial: 'add_poi_modal', locals: {delegate_country: delegate.country, delegate_to_id: delegate.id} )

:javascript
  $(document).ready(function(){
    $( "#modal_link_#{delegate.country}" ).click(function() {
      $("#modal_#{delegate.country}").openModal();
    });
  });

app/views/speechlist/add_poi.js.erb
$("#modal_<%= escape_javascript(@delegate_to_country) %>").closeModal();
$('#session_content').html( "<%= escape_javascript( render 'speaker_list') %>")
Materialize.toast("POI added for <%= escape_javascript(@delegate_to_country) %> !", 4000);

app/views/speechlist/complete.js.erb
$('#modal1').closeModal();
$('.speak-list-modal').html( "<%= escape_javascript( render 'add_to_speaker_list_modal') %>")
$('#session_content').html( "<%= escape_javascript( render 'speaker_list') %>")

app/views/speechlist/delete_mark.js.erb
$('#session_content').html( "<%= escape_javascript( render 'speaker_list') %>")
Materialize.toast("Speech by <%= escape_javascript(@delegate_country) %> has been deleted ! ", 4000);

app/views/speechlist/delete_poi.js.erb
$('#session_content').html( "<%= escape_javascript( render 'speaker_list') %>")
Materialize.toast("POI by <%= escape_javascript(@delegate_from) %> for <%= escape_javascript(@delegate_to.country) %> has been deleted ! ", 4000);

app/views/speechlist/filter.js.erb
$('#session_content').html( "<%= escape_javascript( render(partial: 'filter_list', locals: {delegates: @delegates})) %>")
$('.collapsible').collapsible({
      accordion : false
    });

app/views/speechlist/index.html.haml
.row
  .col.s12
    .card.blue.lighten-2
      .card-content.white-text
        %span.card-title#session-title
          Speaker's List
          .input-field
            %input#filter-countries.validate{:placeholder => "Search Country", :type => "text"}
        .speak-list-modal
          = render 'add_to_speaker_list_modal'
        #session_content
          = render 'speaker_list'
    = render 'fab'

:javascript
  $(document).ready(function() {
    $('#filter-countries').on(
      {
        input: function(){
          if ($(this).val() != "") {
            $('#session_content').html("#{escape_javascript(render 'shared/circular_loader')} ");
            $.ajax({
               url: "#{filter_speechlist_index_path}",
               data: {
                   country_name: $(this).val()
               },
               dataType: "script"
          });
          } else if ($(this).val() == "") {
            $('#session_content').html("#{escape_javascript(render 'speaker_list')}");
          }
        },
        change: function(){
          if ($(this).val() == "") {
            $('#session_content').html("#{escape_javascript(render 'speaker_list')}");
          }
        }
      });
    });

app/views/speechlist/update_mark.js.erb
$('#session_content').html( "<%= escape_javascript( render 'speaker_list') %>")
Materialize.toast('Speech Score Updated!', 4000);

app/views/speechlist/update_poi.js.erb
Materialize.toast('POI Updated!', 4000);